# welcome to numpy cheatsheet

In [1]:
import numpy as np


In [2]:
myarr=np.array([3,2,1,3,43],np.int32)

In [3]:
myarr

array([ 3,  2,  1,  3, 43])

In [4]:
myarr.shape

(5,)

In [5]:
myarr.dtype


dtype('int32')

#  Array Creation: conversion from other Python Structures

In [7]:
listarray=np.array([[1,2,3],[5,8,5],[3,4,6]])

In [8]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [3, 4, 6]])

In [11]:
listarray.dtype
listarray.shape

(3, 3)

In [13]:
zeros=np.zeros((2,4))

In [14]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
rng=np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace = np.linspace(1,5,12)

In [26]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
emp=np.empty((4,6))

In [28]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261162e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.42417222e-306,
        1.33512648e-306, 7.56596412e-307, 8.34420522e-308]])

In [29]:
emp_like=np.empty_like(lspace)

In [30]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [32]:
ide = np.identity(23)
ide
ide.shape

(23, 23)

In [33]:
arr=np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])